require "user.options"
require "user.colorscheme"
require "user.plugins"
require "user.keymaps"
require "user.treesitter"
require "user.telescope"
require "user.nvim-tree"
require "user.autopairs"
require "user.comments"
require "user.indentline"
require "user.impatient"
require "user.gitsigns"
require "user.cmp"
require "user.lsp"

